version: "3.8"
services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    entrypoint: >
      /bin/sh -c "
        until aws --endpoint-url=http://localstack:4566 dynamodb list-tables; do
          echo 'Aguardando o LocalStack...';
          sleep 5;
        done;
        aws --endpoint-url=http://localstack:4566 dynamodb create-table --region 'us-east-1' --table-name 'pagamento_transacao' --attribute-definitions 'AttributeName=idCliente,AttributeType=S' 'AttributeName=idCarrinho,AttributeType=S' --key-schema 'AttributeName=idCliente,KeyType=HASH' 'AttributeName=idCarrinho,KeyType=RANGE' --provisioned-throughput 'ReadCapacityUnits=5,WriteCapacityUnits=5';
        echo 'Tabela criada com sucesso!'
      "
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  wiremock:
    image: holomekc/wiremock-gui:latest
    container_name: wiremock-gui
    ports:
      - "8080:8080"  # Interface Web GUI (Admin)
      - "8089:8089"  # API do WireMock
    volumes:
      - ./wiremock:/home/wiremock  # Mappings armazenados na pasta local
    environment:
      - WIREMOCK_OPTIONS=--verbose --global-response-templating